# Generated by Django 3.1.6 on 2021-03-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_auto_20210306_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link Above To Read the Blog Post...', max_length=255),
        ),
    ]
